#!/usr/bin/python3
"""this module factorizes numbers in a file"""
import sys
my_arg = sys.argv
with open(my_arg[1]) as foo:
    for num in foo:
        num = int(num)
        for val in range(2, int(num * 0.5) + 1):
            if num % val == 0:
                print(f"{int(num)} = {int(num) // val}*{val}")
                break
